### ISSUE TITLE
Media Queris

### ISSUE THREAD

**Issue by StivenYepesArenas** [PabloGomezCardozo/GomezCardozoMLiebre#1]
Hola, Pablo me parece que esta super genial tu proyecto, solo tengo una obcervacion y es que cuando lo abro no me muestra los 4 elementos por pantalla inicialmente, tengo que utilizar las herramientas de desarrollado y modificar el tamaño para que los tome.  Lo menciono por que en otro proyectos me abren la vista de los 4 artículos. 

Saludos

**Comment by PabloGomezCardozo** [comment]
Hola Estiven, gracias por tu comentario. Yo consideré para laptop desde 1280px. Luego de tu observación modifiqué el breakpoint y lo bajé a 992px. Cuando puedas, por favor ingresá nuevamente a la página para verificar que tomó el cambio. Y si estas de acuerdo con la modificación, cerrar luego el Issue.
Gracias!

**Comment by StivenYepesArenas** [comment]
Listo, perfecto. 

Nospi
